DROP TABLE SPORT CASCADE CONSTRAINTS PURGE;
DROP TABLE PERSON CASCADE CONSTRAINTS PURGE;


CREATE TABLE SPORT(
    Sport_ID NUMBER(4),
    Sport_NAME VARCHAR(50) NOT NULL, 
    Sport_DETAILS VARCHAR(50),
    Sport_DATE NUMBER(4),
    CONSTRAINT Sport_ID_FK PRIMARY KEY(Sport_ID)
);

CREATE TABLE PERSON(
    Person_ID NUMBER(4),
    Person_NAME VARCHAR NOT NULL(50),
    Perosn_EMAIL VARCHAR NOT NULL(50),
    Person_Position NUMBER NOT NULL(4),
    CONSTRAINT customer_custid_pk PRIMARY KEY(Person_ID),
    CONSTRAINT Person_Position_fk FOREIGN KEY (Person_Position),
);
